version: '3'

volumes:
  open_exploit_database_scraping_local_postgres_data: {}
  open_exploit_database_scraping_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: open_exploit_database_scraping_local_django
    container_name: open_exploit_database_scraping_local_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: open_exploit_database_scraping_production_postgres
    container_name: open_exploit_database_scraping_local_postgres
    volumes:
      - open_exploit_database_scraping_local_postgres_data:/var/lib/postgresql/data
      - open_exploit_database_scraping_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: open_exploit_database_scraping_local_docs
    container_name: open_exploit_database_scraping_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./open_exploit_database_scraping:/app/open_exploit_database_scraping:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: open_exploit_database_scraping_local_mailhog
    ports:
      - "8025:8025"