version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}
  volume_staticfiles: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: open_exploit_database_scraping_production_django
    volumes:
      - production_django_media:/app/open_exploit_database_scraping/media
      - volume_staticfiles:/var/staticfiles:z
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: open_exploit_database_scraping_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

 #traefik:
 #   build:
 #     context: .
 #     dockerfile: ./compose/production/traefik/Dockerfile
 #   image: open_exploit_database_scraping_production_traefik
 #   depends_on:
 #     - django
 #   volumes:
 #     - production_traefik:/etc/traefik/acme
 #   ports:
 #     - '0.0.0.0:80:80'
 #     - '0.0.0.0:443:443'

  redis:
    image: redis:6

  nginx:
    image: nginx:1.15
    restart: unless-stopped
    depends_on:
        - django
    ports:
        # Map standard HTTP/HTTPS ports from the host
        # to the NGINX container.
        - 80:80
        - 443:443
    volumes:
        - /opt/ssl:/etc/ssl
        - ./compose/production/nginx/dcc.conf:/etc/nginx/conf.d/dcc.conf
        - volume_staticfiles:/var/staticfiles
          #- production_mediafiles:/var/mediafiles
        - ./uploads:/var/mediafiles/uploads
    # environment: # NOTE: Without
    #     - WEB_SERVER_NAME
    #     - FORCE_SCRIPT_NAME
    env_file:
      - ./.envs/.production/.nginx

#  nginx:
#    build:
#      context: .
#      dockerfile: ./compose/production/nginx/Dockerfile
#    image: open_exploit_database_scraping_local_nginx
#    depends_on:
#      - django
#    volumes:
#       - production_django_media:/usr/share/nginx/media:ro
